-- 清空表的:  --
DROP TABLE `xt_access`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_address`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_bonus`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_chongzhi`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_cody`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_cptype`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_fck`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_fck_shop`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_fee`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_fenhong`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_form`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_form_class`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_gouwu`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_gp`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_gp1`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_history`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_huikui`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_inout`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_jiadan`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_jydt`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_msg`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_news_a`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_news_class`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_peng`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_plan`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_product`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_promo`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_times`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_tiqu`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_ulevel`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_xiaof`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_zhuanj`;
-- <fen> --
